version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sova
    ports:
      - 5432:5432
    networks:
      - sova_net
  web:
    build: ./web
    command: flask run -h 0.0.0.0
    volumes:
      - ./web/app/:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - sova_net

networks:
  sova_net:
volumes:
  postgres_data: